/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppTable: typeof import('./src/components/AppTable.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Carts: typeof import('./src/components/carts.vue')['default']
    CRUDDialog: typeof import('./src/components/dialogs/CRUDDialog.vue')['default']
    Feed: typeof import('./src/components/Feed.vue')['default']
    FeedExample: typeof import('./src/components/FeedExample.vue')['default']
    KpiCard: typeof import('./src/components/KpiCard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PolarAreaChart: typeof import('./src/components/PolarAreaChart.vue')['default']
    Posts: typeof import('./src/components/posts.vue')['default']
    Products: typeof import('./src/components/products.vue')['default']
    Profile: typeof import('./src/components/profile.vue')['default']
    RecentList: typeof import('./src/components/RecentList.vue')['default']
    Recipes: typeof import('./src/components/recipes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    StateCard: typeof import('./src/components/StateCard.vue')['default']
    Users: typeof import('./src/components/users.vue')['default']
  }
}
