/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppTable: typeof import('./src/components/AppTable.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    Credentials: typeof import('./src/components/credentials.vue')['default']
    CRUDDialog: typeof import('./src/components/dialogs/CRUDDialog.vue')['default']
    Feed: typeof import('./src/components/Feed.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PolarAreaChart: typeof import('./src/components/PolarAreaChart.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    StateCard: typeof import('./src/components/StateCard.vue')['default']
  }
}
